config/routes.rb
Rails.application.routes.draw do

  root to: "blog_posts#index"
  resources :blog_posts, except: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :main_picture # one-to-one relationship
  has_many_attached :uploads # one-to-many relationship

  def is_attachment_valid_image?
    main_picture.blob.content_type.start_with?('image/')
  end

  # def is_attachment_valid_pdf?()
  #   main_picture.blob.content_type == 'application/pdf'
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    @posts = BlogPost.all
  end

  def new
    @post = BlogPost.new
  end

  def create
    # create db entry using the blog_post_params, which automatically creates attached the entries for main and uploads
    @post = BlogPost.new(blog_post_params)

    # check if there is a main image attached; if so, check that it has a valid extension; if not, delete
    if @post.main_picture.attached?
      unless @post.is_attachment_valid_image?
        @post.main_picture.purge
      end
    end

    # check that there are uploads attached; if so, check each one and see if it's the right format; if not, delete
    if  @post.uploads.attached?
      @post.uploads.each do |upload|
        unless upload.blob.content_type == 'application/pdf' || upload.blob.content_type.start_with?('image/')
          upload.purge
        end
      end
    end

    # persist the post and redirect to the index view
    if @post.save
      redirect_to blog_posts_path
    end

  end

  def edit
    @post
  end

  def update

  end

  def destroy

  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :main_picture, uploads: [])
  end

  def set_post
    @post = BlogPost.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/edit.html.haml
%h1 BlogPosts#edit
%p Find me in app/views/blog_posts/edit.html.haml

app/views/blog_posts/index.html.haml
.container.borer-green
  %h1.border-gree BlogPosts

  %div.border-gren.posts-container
    -unless @posts.empty?
      -@posts.each do |post|
        %div.bordr-red
          %p=post.title
          %p=post.content
          -if post.main_picture.attached?
            %article.main-image-wrapper.bordr-red
              =image_tag(post.main_picture)

          -if post.uploads.attached?
            Uploads:
            %article.uploads-wrapper.border-green
              -post.uploads.each do |upload|
                -if upload.blob.content_type.start_with?("image/")
                  =image_tag(upload)
                -elsif upload.blob.content_type == 'application/pdf'
                  = link_to 'View file', upload, target: :blank


          =link_to 'Edit', edit_blog_post_path(post)


  %button.create-button=link_to 'Create', new_blog_post_path

app/views/blog_posts/new.html.haml
%h1 BlogPosts#new

=form_with model: @post, local: true, class: 'border-re form-container', id: 'new-post-form' do |form|
  .form-group.borde-green
    = form.text_field :title, placeholder: 'Title'
  .form-group.borer-green
    = form.text_area :content, placeholder: 'Start writing...'
  .form-group.borde-green
    =form.label :main_picture, 'Main Picture'
    =form.file_field :main_picture
  .form-group.borde-green
    =form.label :uploads
    =form.file_field :uploads, multiple: true
  .form-gr
    = form.submit 'Save', class: 'save-button', id: 'new_submit'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStorageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>